services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
     - PORT=8080
     - CONNECTION_STRING=root:123456@tcp(db:3306)/plantapi?charset=utf8&parseTime=True&loc=Local
     - JWT_SECRET=RahasiaJWT

  db:
    image: bitnami/mysql
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=plantapi
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p123456", "-e", "show schemas"]
      interval: 20s