name: Running unit test
on:
  pull_request:
  push:
    branches:
      - development
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: run unit test
        run: go test ./... -cover
